/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.9.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import {HexBinary, Boolean} from "./types";
import {InstantiateMsg, ExecuteMsg, VdataHex, QueryMsg, MigrateMsg, ConfigResponse, ArrayOfUserFriendlyValidator, UserFriendlyValidator} from "./TonbridgeValidator.types";
export interface TonbridgeValidatorReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  getCandidatesForValidators: ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: number;
  }) => Promise<ArrayOfUserFriendlyValidator>;
  getValidators: ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: string;
  }) => Promise<ArrayOfUserFriendlyValidator>;
  isVerifiedBlock: ({
    rootHash
  }: {
    rootHash: HexBinary;
  }) => Promise<Boolean>;
  isSignedByValidator: ({
    rootHash,
    validatorNodeId
  }: {
    rootHash: HexBinary;
    validatorNodeId: HexBinary;
  }) => Promise<Boolean>;
  nextValidatorUpdated: () => Promise<Boolean>;
}
export class TonbridgeValidatorQueryClient implements TonbridgeValidatorReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.getCandidatesForValidators = this.getCandidatesForValidators.bind(this);
    this.getValidators = this.getValidators.bind(this);
    this.isVerifiedBlock = this.isVerifiedBlock.bind(this);
    this.isSignedByValidator = this.isSignedByValidator.bind(this);
    this.nextValidatorUpdated = this.nextValidatorUpdated.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  getCandidatesForValidators = async ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: number;
  }): Promise<ArrayOfUserFriendlyValidator> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_candidates_for_validators: {
        limit,
        order,
        start_after: startAfter
      }
    });
  };
  getValidators = async ({
    limit,
    order,
    startAfter
  }: {
    limit?: number;
    order?: number;
    startAfter?: string;
  }): Promise<ArrayOfUserFriendlyValidator> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_validators: {
        limit,
        order,
        start_after: startAfter
      }
    });
  };
  isVerifiedBlock = async ({
    rootHash
  }: {
    rootHash: HexBinary;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_verified_block: {
        root_hash: rootHash
      }
    });
  };
  isSignedByValidator = async ({
    rootHash,
    validatorNodeId
  }: {
    rootHash: HexBinary;
    validatorNodeId: HexBinary;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_signed_by_validator: {
        root_hash: rootHash,
        validator_node_id: validatorNodeId
      }
    });
  };
  nextValidatorUpdated = async (): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      next_validator_updated: {}
    });
  };
}
export interface TonbridgeValidatorInterface extends TonbridgeValidatorReadOnlyInterface {
  contractAddress: string;
  sender: string;
  prepareNewKeyBlock: ({
    keyblockBoc
  }: {
    keyblockBoc: HexBinary;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  resetValidatorSet: ({
    boc
  }: {
    boc: HexBinary;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  verifyKeyBlock: ({
    fileHash,
    rootHash,
    vdata
  }: {
    fileHash: HexBinary;
    rootHash: HexBinary;
    vdata: VdataHex[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  verifyMasterchainBlockByValidatorSignatures: ({
    blockHeaderProof,
    fileHash,
    vdata
  }: {
    blockHeaderProof: HexBinary;
    fileHash: HexBinary;
    vdata: VdataHex[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  verifyShardBlocks: ({
    mcBlockRootHash,
    shardProofLinks
  }: {
    mcBlockRootHash: HexBinary;
    shardProofLinks: HexBinary[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setVerifiedBlock: ({
    rootHash,
    seqNo
  }: {
    rootHash: HexBinary;
    seqNo: number;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class TonbridgeValidatorClient extends TonbridgeValidatorQueryClient implements TonbridgeValidatorInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.prepareNewKeyBlock = this.prepareNewKeyBlock.bind(this);
    this.resetValidatorSet = this.resetValidatorSet.bind(this);
    this.verifyKeyBlock = this.verifyKeyBlock.bind(this);
    this.verifyMasterchainBlockByValidatorSignatures = this.verifyMasterchainBlockByValidatorSignatures.bind(this);
    this.verifyShardBlocks = this.verifyShardBlocks.bind(this);
    this.setVerifiedBlock = this.setVerifiedBlock.bind(this);
  }

  prepareNewKeyBlock = async ({
    keyblockBoc
  }: {
    keyblockBoc: HexBinary;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      prepare_new_key_block: {
        keyblock_boc: keyblockBoc
      }
    }, _fee, _memo, _funds);
  };
  resetValidatorSet = async ({
    boc
  }: {
    boc: HexBinary;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      reset_validator_set: {
        boc
      }
    }, _fee, _memo, _funds);
  };
  verifyKeyBlock = async ({
    fileHash,
    rootHash,
    vdata
  }: {
    fileHash: HexBinary;
    rootHash: HexBinary;
    vdata: VdataHex[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      verify_key_block: {
        file_hash: fileHash,
        root_hash: rootHash,
        vdata
      }
    }, _fee, _memo, _funds);
  };
  verifyMasterchainBlockByValidatorSignatures = async ({
    blockHeaderProof,
    fileHash,
    vdata
  }: {
    blockHeaderProof: HexBinary;
    fileHash: HexBinary;
    vdata: VdataHex[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      verify_masterchain_block_by_validator_signatures: {
        block_header_proof: blockHeaderProof,
        file_hash: fileHash,
        vdata
      }
    }, _fee, _memo, _funds);
  };
  verifyShardBlocks = async ({
    mcBlockRootHash,
    shardProofLinks
  }: {
    mcBlockRootHash: HexBinary;
    shardProofLinks: HexBinary[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      verify_shard_blocks: {
        mc_block_root_hash: mcBlockRootHash,
        shard_proof_links: shardProofLinks
      }
    }, _fee, _memo, _funds);
  };
  setVerifiedBlock = async ({
    rootHash,
    seqNo
  }: {
    rootHash: HexBinary;
    seqNo: number;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_verified_block: {
        root_hash: rootHash,
        seq_no: seqNo
      }
    }, _fee, _memo, _funds);
  };
}